name: Example workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build image
        run: |
          docker build -t testactions .
      - name: Test
        run: bash tools/test.sh
      - name: Upload test results
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: TestResults

        

